const ActionType = {
  FETCH_FLIGHTS: 'FETCH_FLIGHTS',
  FETCH_FLIGHTS_SUCCESS: 'FETCH_FLIGHTS_SUCCESS',
  FETCH_FLIGHTS_ERROR: 'FETCH_FLIGHTS_ERROR',
  ADD_FLIGHT: 'ADD_FLIGHT'
};

export default ActionType;