const ActionType = {
  FETCH_FLIGHTS: 'FETCH_FLIGHTS',
  FETCH_FLIGHTS_SUCCESS: 'FETCH_FLIGHTS_SUCCESS',
  FETCH_FLIGHTS_ERROR: 'FETCH_FLIGHTS_ERROR',
  ADD_FLIGHT: 'ADD_FLIGHT',
  ADD_FLIGHT_SUCCESS: 'ADD_FLIGHT_SUCCESS',
  SHOW_ALERT: 'SHOW_ALERT',
  DISMISS_ALERT: 'DISMISS_ALERT'
};

export default ActionType;